// 마이너 아르카나 56장 = 4수트(Wands/Cups/Swords/Pentacles) × 14랭크(Ace~10, Page~King)
//
// 데이터가 많아 한 장을 배열 5칸으로 압축했다. 순서는 항상 고정이다:
//   [ 랭크, 정방향 키워드, 정방향 본문, 역방향 키워드, 역방향 본문 ]
// 아래 buildSuit() 가 이 배열을 majors.js 와 똑같은 { n, name, el, up, rev } 모양으로 바꿔준다.
// → 엔진 입장에서는 메이저 22장과 마이너 56장이 완전히 같은 형태라 분기가 필요 없다.

export const SUITS = {
  wands:     { name: 'Wands',     el: 'fire',  domain: 'energy, drive and creative work' },
  cups:      { name: 'Cups',      el: 'water', domain: 'feelings, relationships and intuition' },
  swords:    { name: 'Swords',    el: 'air',   domain: 'thought, truth and conflict' },
  pentacles: { name: 'Pentacles', el: 'earth', domain: 'money, work, health and the material world' },
}

export const RANKS = ['Ace', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Page', 'Knight', 'Queen', 'King']

const WANDS = [
  ['Ace', 'spark · new opportunity · raw potential',
    'A spark lands — an idea, an invitation, a sudden appetite to build something. It is early and unformed, and it will not wait politely. Act on it while it is still hot.',
    'false start · lost spark · hesitation',
    'The idea is there but nothing is catching. Either the timing is wrong or you are waiting for permission that is not coming. Start smaller rather than not at all.'],
  ['Two', 'planning · first move · weighing the world',
    'You are holding the world in your hand and looking at the horizon. The plan is real, the courage is nearly there. This card asks for the decision, not more research.',
    'fear of the unknown · playing safe · stuck planning',
    'You have planned this to death because planning feels like progress. The comfortable option is quietly becoming the expensive one.'],
  ['Three', 'expansion · foresight · ships coming in',
    'The first move is made and now you watch it travel. Wider horizons, a bigger arena, results arriving from something you set going earlier. Keep the long view.',
    'delays · narrow vision · setback abroad',
    'Something you sent out is coming back slower or smaller than expected. The plan is not wrong, the scope is. Widen it or wait it out.'],
  ['Four', 'celebration · stability · homecoming',
    'A milestone worth marking, and people to mark it with. Home, community, a threshold crossed safely. Let yourself stop and enjoy the solid ground.',
    'unstable foundation · transition · postponed joy',
    'The ground is not as settled as it looks, or a celebration is being deferred again. Sort the foundation before you build the next floor on it.'],
  ['Five', 'friction · competition · noisy disagreement',
    'Everyone is talking and nobody is listening. This is scrappy rather than dangerous — clashing egos and crossed purposes. Find out what people actually want underneath the noise.',
    'avoiding conflict · inner conflict · truce',
    'Either the fight is winding down, or you are swallowing a disagreement to keep the peace. Unspoken conflict does not disappear, it just goes underground.'],
  ['Six', 'recognition · public win · momentum',
    'You are seen, and it is deserved. A win becomes visible to other people — approval, progress, a small parade. Accept it without deflecting.',
    'lack of recognition · self-doubt · deflated win',
    'You did the work and someone else got the credit, or you cannot let yourself feel the win. Say plainly what you contributed.'],
  ['Seven', 'defending your ground · perseverance · conviction',
    'You are on higher ground and being challenged from below. You can hold this position, but only if you decide it is worth holding. Do not defend something you no longer want.',
    'overwhelmed · giving up · worn down',
    'The defence is costing more than the thing being defended. Either get support or step off the hill deliberately rather than falling off it.'],
  ['Eight', 'speed · news arriving · sudden movement',
    'Things move fast now. Messages land, delays break, everything that was stuck starts travelling at once. Be ready to answer quickly.',
    'delays · scattered effort · missed timing',
    'Momentum has stalled or gone in five directions at once. Slow down deliberately and re-aim rather than firing again.'],
  ['Nine', 'resilience · one more round · guarded',
    'You are tired and still standing, and standing is the achievement. The last stretch is nearly done. Guard your energy, not your pride.',
    'exhaustion · paranoia · defensiveness',
    'The armour has become the problem. You are defending against threats that already passed. Put it down before it costs you the people still on your side.'],
  ['Ten', 'burden · overload · carrying too much',
    'You are carrying everything and can barely see over it. Some of this load is not actually yours. Put down what you picked up out of habit.',
    'delegating · releasing the load · breaking point',
    'Either you are finally handing things off, or you are about to drop all of it at once. Choose the first one while you still can.'],
  ['Page', 'curiosity · new venture · restless energy',
    'An eager beginning — a new interest, a message that opens a door, permission to be a beginner. Enthusiasm is the resource here, not skill.',
    'procrastination · scattered interest · flat news',
    'The excitement fizzled before it became anything. Pick one of the many started things and finish only that.'],
  ['Knight', 'bold action · adventure · charge',
    'Fast, hot, fearless movement. This is the card of going for it — travel, a leap, a passionate push. Speed is the advantage as long as the direction is right.',
    'recklessness · burnout · frustration',
    'All heat and no aim. Rushing here breaks something. Take the aggression out and the same energy becomes useful.'],
  ['Queen', 'warm confidence · magnetism · self-assurance',
    'Someone who knows exactly what they are worth and makes room for others anyway. Be that. Confidence plus warmth opens doors that pressure cannot.',
    'insecurity · jealousy · demanding',
    'Confidence is being faked, and it is coming out as comparison or control. Deal with the doubt directly instead of managing everyone around it.'],
  ['King', 'vision · leadership · long game',
    'Someone with a vision who can actually get people to build it. Take the lead. This is a card for founders, decisions and setting direction.',
    'domineering · impatience · unrealistic expectations',
    'Vision has hardened into pressure. Expecting everyone to move at your speed is not leadership, it is a bottleneck.'],
]

const CUPS = [
  ['Ace', 'new feeling · open heart · emotional beginning',
    'The cup overflows. New love, renewed affection, a creative feeling that wants somewhere to go. Let it be felt before you decide what it means.',
    'blocked feeling · emptiness · guarded heart',
    'The feeling is there but you have the lid on it. Something got hurt and closed. Nothing flows back in until a little flows out.'],
  ['Two', 'mutual connection · partnership · attraction',
    'Two people meeting each other equally — romance, friendship or a genuine partnership. What makes this card work is that both sides are offering, not just one.',
    'imbalance · broken communication · one-sided',
    'One person is carrying this. The connection is real but the effort is not shared. Say the thing that has gone unsaid.'],
  ['Three', 'friendship · celebration · belonging',
    'Your people. Shared joy, a reunion, the relief of being genuinely known. Reach out — this card works when it is acted on rather than felt.',
    'gossip · exclusion · crowded out',
    'The group dynamic has turned. Gossip, a third person in the way, or a slow drift out of a circle you used to belong to.'],
  ['Four', 'discontent · apathy · looking away',
    'Something good is being offered and you cannot feel interested in it. This is not ingratitude, it is saturation. Notice what is already in front of you.',
    'new interest · acceptance · waking up',
    'The numbness is lifting and appetite is coming back. Say yes to the next small offer even if it feels premature.'],
  ['Five', 'grief · regret · what was lost',
    'Three cups spilled and two still standing. The loss is real and worth grieving. But turn around eventually — you are facing the wrong direction.',
    'acceptance · moving on · peace with it',
    'The grief is loosening. You are starting to see what remains rather than only what went. Let that be enough for now.'],
  ['Six', 'nostalgia · innocence · a familiar face',
    'The past comes back kindly — an old friend, a childhood memory, a gentleness you had forgotten. Take the comfort. Do not move in.',
    'stuck in the past · rosy memory · moving forward',
    'A memory is being edited into something better than it was, and it is keeping you from the present. Or you are finally putting it down. Both live here.'],
  ['Seven', 'too many options · fantasy · wishful thinking',
    'Seven cups and only one has anything real in it. The choices are dazzling and mostly imaginary. Test each one against what is actually available.',
    'clarity · decision made · illusion breaks',
    'The fog clears and one option is obviously the real one. Commit before the other six start looking good again.'],
  ['Eight', 'walking away · seeking more · quiet exit',
    'You leave something that is not bad, just no longer enough. There is nothing to blame here. Deeper meaning is elsewhere and you know which direction.',
    'fear of leaving · drifting back · indecision',
    'You have one foot out of the door and you keep pulling it back. The staying is not a choice yet, it is inertia.'],
  ['Nine', 'contentment · a wish granted · satisfaction',
    'The wish card. Something you wanted lands, and it feels as good as you hoped. Enjoy it out loud — satisfaction unspoken tends to fade fast.',
    'unfulfilled wish · shallow pleasure · wanting more',
    'You got it and it did not fill the hole, or it has not arrived yet. Check whether you wished for the thing or for what you thought it would fix.'],
  ['Ten', 'emotional fulfilment · family · lasting happiness',
    'The settled kind of happy — belonging, home, people who stay. Not a peak but a floor. Protect it; this is the thing everything else is for.',
    'disconnection · strained home · misaligned values',
    'The picture looks right from outside and does not feel right from inside. Something in the household or the relationship is being performed rather than lived.'],
  ['Page', 'a message · creative curiosity · tender beginning',
    'A small, sincere emotional opening — a message, a crush, an intuitive nudge, a creative idea that feels personal. Do not over-analyse it yet.',
    'immaturity · escapism · creative block',
    'Feelings are being handled clumsily, yours or someone else. Or imagination has become somewhere to hide rather than something to make with.'],
  ['Knight', 'romance · following the heart · an offer',
    'Someone arrives with an offer made of feeling — an invitation, a confession, a romantic move. Charming and genuine, though not always practical.',
    'moodiness · empty promises · idealising',
    'The feeling is loud and the follow-through is missing. Watch what is done, not what is declared.'],
  ['Queen', 'compassion · emotional depth · safe harbour',
    'Deep feeling held steadily. Someone people bring their real problems to. Be that for someone, or go find that person — you are allowed to need it too.',
    'over-giving · codependency · emotional exhaustion',
    'Caring has tipped into absorbing. You are managing other people feelings at the cost of your own. Boundaries are not a withdrawal of love.'],
  ['King', 'emotional mastery · calm · generous wisdom',
    'Feeling everything and being run by none of it. Steady, diplomatic, kind under pressure. This is the card for handling something delicate well.',
    'volatility · manipulation · shut down',
    'Emotion is being used as a lever, or locked away entirely. Coldness and outburst are the same failure here — the feeling is not being handled honestly.'],
]

const SWORDS = [
  ['Ace', 'breakthrough · clarity · the truth cuts',
    'A sudden clean insight. The confusion breaks and you can see the actual shape of things. Use it now — this kind of clarity has a short shelf life.',
    'confusion · clouded judgement · bad information',
    'You are reasoning hard on top of a faulty fact. Go back and check the premise before you build another conclusion on it.'],
  ['Two', 'stalemate · blocked choice · not looking',
    'Blindfolded with two blades up. You are refusing to choose because choosing means losing one option. Take the blindfold off first; the decision gets easier with information.',
    'indecision breaking · information revealed · overwhelm',
    'Something is about to be revealed that makes the choice for you. Or the pressure of not deciding has become worse than deciding.'],
  ['Three', 'heartbreak · painful truth · sorrow',
    'A clean, sharp hurt — usually the truth arriving. It is not the end of anything except the illusion. Grieve it properly instead of explaining it away.',
    'healing · forgiveness · releasing the hurt',
    'The blade is coming out. Slow recovery, forgiveness that is chosen rather than felt, pain that finally has a past tense.'],
  ['Four', 'rest · retreat · deliberate stillness',
    'Stop. Not defeat — recovery. This card actively prescribes doing nothing for a while. The problem will be smaller after you sleep.',
    'burnout · restlessness · forced back too soon',
    'You skipped the rest and it is showing, or you cannot make yourself stop. Exhaustion does not negotiate. It only postpones.'],
  ['Five', 'hollow victory · conflict · winning badly',
    'You can win this and lose everything worth winning it for. Check the cost of being right. Some arguments are more expensive than the point being made.',
    'reconciliation · making amends · letting it go',
    'The fight is ending. Someone is willing to repair it, and pride is the only thing left in the way.'],
  ['Six', 'transition · calmer water · moving on',
    'You are moving away from something rough toward something quieter. It is not dramatic and it is not finished, but the water is getting smoother.',
    'stuck · carrying baggage · resisting the move',
    'The move is not happening, or you have brought the whole problem with you. Some things cannot come along.'],
  ['Seven', 'strategy · going it alone · something concealed',
    'Someone is being clever rather than straight — possibly you. There may be a good reason, but check whether the plan needs secrecy or just prefers it.',
    'exposure · confession · conscience',
    'The hidden thing surfaces. Getting ahead of it costs far less than being caught by it.'],
  ['Eight', 'self-imposed limits · feeling trapped · powerlessness',
    'Bound and blindfolded, with the ropes loose and the way out unguarded. The trap is mostly built out of belief. Test one bar of the cage.',
    'freeing yourself · new perspective · limits dissolve',
    'You are working out that you were never actually tied. Small experiments in freedom now, not one grand escape.'],
  ['Nine', 'anxiety · sleepless worry · dread',
    'The three-in-the-morning card. Fear well past the size of the facts. Say the worry out loud to someone — it shrinks dramatically in daylight.',
    'relief · asking for help · worry releasing',
    'The dread is loosening its grip, usually because you finally told someone. Keep telling someone.'],
  ['Ten', 'painful ending · rock bottom · finality',
    'It is over and it was not gentle. But ten blades means nothing worse is coming — this is the floor, and the sun is already rising in the card.',
    'recovery · the worst has passed · slow return',
    'You are getting up. Do not rush it and do not go back to check whether it is really over. It is.'],
  ['Page', 'curiosity · vigilance · new information',
    'Sharp, restless attention. Questions, research, noticing what others missed. Ask the awkward question — you are right to be curious.',
    'gossip · hasty words · scattered thinking',
    'Information is being handled carelessly — said too fast, spread too far, or half-understood. Slow the mouth down.'],
  ['Knight', 'drive · fast action · bluntness',
    'Charging in with total conviction. Decisive and effective, and not especially interested in anyone feelings about it. Useful now, expensive later.',
    'aggression · recklessness · burning out',
    'Speed has become force. You are cutting through things that needed handling carefully. Slow down before it costs a relationship.'],
  ['Queen', 'clear thinking · honesty · firm boundaries',
    'Perceptive, direct and hard to fool. Says the true thing plainly. Be this — clarity is kinder than a comfortable lie.',
    'coldness · harsh words · bitterness',
    'Directness has turned into a weapon. Old hurt is sharpening the honesty into something that cuts more than it clarifies.'],
  ['King', 'judgement · intellectual authority · truth',
    'Clear-eyed authority. Decisions made on evidence, held without ego. Seek this person out, or be them for someone who needs it.',
    'misuse of power · cold logic · manipulation',
    'Intelligence used to dominate rather than clarify. Being technically right is being used to avoid being fair.'],
]

const PENTACLES = [
  ['Ace', 'opportunity · new resource · solid start',
    'A tangible opening — a job, an offer, money, a practical chance. This one has substance. Take it and treat it seriously from day one.',
    'missed chance · scarcity thinking · shaky start',
    'An opportunity slips, or fear of not-enough makes you say no to something worth taking. Check whether the risk is real or inherited.'],
  ['Two', 'juggling · adaptability · balance in motion',
    'Two things in the air and you are managing both, just about. It works while you keep moving. Do not add a third.',
    'overwhelm · dropped ball · disorganised',
    'Something has hit the floor. You cannot carry all of it — decide what gets put down deliberately.'],
  ['Three', 'collaboration · craft · being good at it',
    'Skill recognised and put to work with other people. The result needs more than one set of hands. Ask for the help; it makes the work better, not weaker.',
    'poor teamwork · sloppy work · going it alone',
    'The pieces are not fitting — mismatched standards or someone working in isolation. Get everyone looking at the same version of it.'],
  ['Four', 'security · saving · holding tight',
    'Holding on to what you have. Sensible for now, and worth watching. Security that stops you moving has stopped being security.',
    'greed · fear of loss · letting go',
    'The grip is too tight, on money, control or a person. Or you are finally loosening it. Either way the holding was costing something.'],
  ['Five', 'hardship · exclusion · out in the cold',
    'A rough patch — money, health or feeling shut out. Look at the card: there is a lit window right there. Help exists and you have not asked.',
    'recovery · help arrives · end of the hard part',
    'The worst of it is turning. Support shows up, often from an unexpected direction. Accept it without paying for it in pride.'],
  ['Six', 'generosity · fair exchange · support',
    'Giving and receiving in reasonable proportion. Help offered, help accepted. Whichever side you are on today, the balance will change later.',
    'strings attached · imbalance · debt',
    'The generosity has a price on it, or the giving has become one-directional. Name the terms out loud.'],
  ['Seven', 'patience · assessment · waiting for growth',
    'You have planted and now you stare at it. Nothing is wrong — this is just the boring middle. Assess honestly, then let it grow.',
    'impatience · poor return · sunk cost',
    'You are pulling it up to check the roots, or pouring effort into something that has stopped paying back. Cut or commit.'],
  ['Eight', 'craft · practice · getting better',
    'Head down, repetitions in. Skill built by doing the same thing until it is good. Unglamorous and exactly right for this moment.',
    'perfectionism · uninspired work · going through the motions',
    'The repetition has become empty, or nothing is ever finished because it is never perfect. Ship it at ninety percent.'],
  ['Nine', 'independence · earned comfort · self-sufficiency',
    'You built this yourself and you can enjoy it alone. Financial or personal independence, and the quiet confidence that comes with it.',
    'over-invested in work · dependence · unenjoyed reward',
    'The comfort is there and you have no time to sit in it, or the independence is not as independent as it looks.'],
  ['Ten', 'lasting wealth · legacy · family security',
    'The long-term version of success — built to outlast you. Family, property, stability handed forward. Think in decades here.',
    'financial loss · family conflict · short-term thinking',
    'Money and family are tangled together, and it is straining both. Or a long-term plan is being traded for a quick result.'],
  ['Page', 'study · new venture · ambition',
    'The beginning of something practical — a course, a side project, a first real plan. Ambitious and unproven. Start, then keep starting.',
    'procrastination · distraction · no commitment',
    'The plan exists and the work has not begun. The gap between intention and action is where this card lives.'],
  ['Knight', 'reliability · steady work · method',
    'Slow, dependable, unexciting progress. The least dramatic card in the deck and one of the most effective. Just keep doing it.',
    'stagnation · boredom · over-caution',
    'Steady has become stuck. The routine that was protecting you is now the ceiling. Change one variable.'],
  ['Queen', 'practical care · resourcefulness · comfort',
    'Someone who makes things work and makes people comfortable while doing it. Grounded, capable, generous with real help rather than advice.',
    'self-neglect · work-life imbalance · smothering',
    'You are looking after everything except your own body and time. Practical care has to include you or it runs out.'],
  ['King', 'abundance · business sense · stability',
    'Proven, prosperous, unbothered. Good judgement about money and resources. A good moment for a business decision or an investment of effort.',
    'materialism · stubbornness · controlling',
    'Success measured only in what it produces. Or a refusal to change an approach that used to work and no longer does.'],
]

// 위 5칸 배열 → { n, name, el, up, rev } 표준 카드 객체로 변환
function buildSuit(suitKey, rows) {
  const suit = SUITS[suitKey]
  return rows.map(([rank, upK, upT, revK, revT], i) => ({
    n: i + 1,                                   // 1..14 (Ace=1, Page=11, Knight=12, Queen=13, King=14)
    rank,
    suit: suitKey,
    name: `${rank} of ${suit.name}`,
    el: suit.el,
    up:  { k: upK,  t: upT },
    rev: { k: revK, t: revT },
  }))
}

export const MINORS = [
  ...buildSuit('wands', WANDS),
  ...buildSuit('cups', CUPS),
  ...buildSuit('swords', SWORDS),
  ...buildSuit('pentacles', PENTACLES),
]
